 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Santa206
 */
public class facturaCabVista extends javax.swing.JFrame {

    /**
     * Creates new form facturaVenta
     */
    public facturaCabVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtfiltrocliente = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtinicio = new javax.swing.JTextField();
        txtfin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnbuscarfactura = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablafactura = new javax.swing.JTable();
        btnaceptar2 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtbuscarproducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablabuscadorproducto = new javax.swing.JTable();
        btnaceptar3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtruc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtestado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidproducto = new javax.swing.JTextField();
        txtnombreproducto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndell = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalle = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtliquidacion5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtliquidacion10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtliquidaciontotal = new javax.swing.JTextField();
        txttotalexenta = new javax.swing.JTextField();
        txttotal5 = new javax.swing.JTextField();
        txttotal10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttotalfactura = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnanular = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        optcontado = new javax.swing.JRadioButton();
        optcredito = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JLabel();
        btnbuscarcliente = new javax.swing.JButton();
        txtidpersonal = new javax.swing.JLabel();
        txtnombrepersonal = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaceptar.setText("ACEPTAR");
        jPanel4.add(btnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 92, 34));

        tablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "NOMBRE", "APELLIDO", "RUC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablacliente);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 495, 200));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));
        jPanel4.add(txtfiltrocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 430, 20));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIO");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, -1));
        jPanel5.add(txtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 11, 70, -1));
        jPanel5.add(txtfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 11, 90, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FIN");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btnbuscarfactura.setText("BUSCAR");
        jPanel5.add(btnbuscarfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 11, -1, -1));

        tablafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nº FACTURA", "FECHA", "CONDICION", "ESTADO", "ID. CLIENTE", "NOMBRE", "APELLIDO", "RUC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablafactura);
        if (tablafactura.getColumnModel().getColumnCount() > 0) {
            tablafactura.getColumnModel().getColumn(0).setResizable(false);
            tablafactura.getColumnModel().getColumn(1).setResizable(false);
            tablafactura.getColumnModel().getColumn(2).setResizable(false);
            tablafactura.getColumnModel().getColumn(3).setResizable(false);
            tablafactura.getColumnModel().getColumn(4).setResizable(false);
            tablafactura.getColumnModel().getColumn(5).setResizable(false);
            tablafactura.getColumnModel().getColumn(6).setResizable(false);
            tablafactura.getColumnModel().getColumn(7).setResizable(false);
            tablafactura.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 41, 680, 280));

        btnaceptar2.setText("ACEPTAR");
        jPanel5.add(btnaceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 100, 40));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BUSCAR");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jPanel6.add(txtbuscarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 39, 570, -1));

        tablabuscadorproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablabuscadorproducto);
        if (tablabuscadorproducto.getColumnModel().getColumnCount() > 0) {
            tablabuscadorproducto.getColumnModel().getColumn(0).setMinWidth(100);
            tablabuscadorproducto.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablabuscadorproducto.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 65, 655, 267));

        btnaceptar3.setText("ACEPTAR");
        jPanel6.add(btnaceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 350, -1, 31));

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 31, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 21, 120, 30));

        jLabel4.setText("Nº FACTURA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, -1));

        jLabel5.setText("CODIGO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel6.setText("NOMBRE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jLabel7.setText("APELLIDO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel8.setText("RUC");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        txtcliente.setEnabled(false);
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 140, -1));

        txtnombre.setEnabled(false);
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 140, -1));

        txtapellido.setEnabled(false);
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 140, -1));

        txtruc.setEnabled(false);
        jPanel1.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 140, -1));

        jLabel9.setText("ESTADO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtestado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtestado.setText("PENDIENTE");
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 30));

        jLabel11.setText("COD PRODUCTO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        txtidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 20));

        txtnombreproducto.setText("NOMBRE PRODUCTO");
        jPanel1.add(txtnombreproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel13.setText("CANTIDAD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
        jPanel1.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 70, -1));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/more.png"))); // NOI18N
        btnadd.setContentAreaFilled(false);
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        btndell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btndell.setContentAreaFilled(false);
        jPanel1.add(btndell, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        tabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "PRODUCTO", "CANTIDAD", "PRECIO", "EXENTA", "5%", "10%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabladetalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabladetalle);
        if (tabladetalle.getColumnModel().getColumnCount() > 0) {
            tabladetalle.getColumnModel().getColumn(0).setResizable(false);
            tabladetalle.getColumnModel().getColumn(0).setPreferredWidth(35);
            tabladetalle.getColumnModel().getColumn(1).setResizable(false);
            tabladetalle.getColumnModel().getColumn(2).setResizable(false);
            tabladetalle.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabladetalle.getColumnModel().getColumn(3).setResizable(false);
            tabladetalle.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabladetalle.getColumnModel().getColumn(4).setResizable(false);
            tabladetalle.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabladetalle.getColumnModel().getColumn(5).setResizable(false);
            tabladetalle.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabladetalle.getColumnModel().getColumn(6).setResizable(false);
            tabladetalle.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 800, 180));

        jLabel14.setText("LID IVA 5%");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 20));

        txtliquidacion5.setText("0");
        txtliquidacion5.setEnabled(false);
        jPanel1.add(txtliquidacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 70, -1));

        jLabel15.setText("10%");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

        txtliquidacion10.setText("0");
        txtliquidacion10.setEnabled(false);
        jPanel1.add(txtliquidacion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 100, -1));

        jLabel16.setText("TOTAL IVA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        txtliquidaciontotal.setText("0");
        txtliquidaciontotal.setEnabled(false);
        jPanel1.add(txtliquidaciontotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 130, -1));

        txttotalexenta.setText("0");
        txttotalexenta.setEnabled(false);
        jPanel1.add(txttotalexenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 140, -1));

        txttotal5.setText("0");
        txttotal5.setEnabled(false);
        jPanel1.add(txttotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 130, -1));

        txttotal10.setText("0");
        txttotal10.setEnabled(false);
        jPanel1.add(txttotal10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 120, -1));

        jLabel17.setText("TOTAL FACTURA");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, 20));

        txttotalfactura.setText("0");
        txttotalfactura.setEnabled(false);
        jPanel1.add(txttotalfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 150, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gest.servicio.png"))); // NOI18N
        btnnuevo.setToolTipText("BOTON NUEVO");
        btnnuevo.setContentAreaFilled(false);
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grabar.png"))); // NOI18N
        btnguardar.setToolTipText("BOTON GUARDAR");
        btnguardar.setContentAreaFilled(false);
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 50, 30));

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Impresora.png"))); // NOI18N
        btnimprimir.setToolTipText("IMPRIMIR FACTURA");
        btnimprimir.setContentAreaFilled(false);
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 70, -1));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscar.setToolTipText("BUSCAR FACTURA");
        btnbuscar.setContentAreaFilled(false);
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 60, 30));

        btnanular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/error.png"))); // NOI18N
        btnanular.setToolTipText("ANULAR FACTURA");
        btnanular.setContentAreaFilled(false);
        jPanel1.add(btnanular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 60, 40));

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-circular.png"))); // NOI18N
        btncancelar.setToolTipText("BOTON CANCELAR");
        btncancelar.setContentAreaFilled(false);
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CONDICION"));

        buttonGroup1.add(optcontado);
        optcontado.setText("CONTADO");
        optcontado.setBorder(null);

        buttonGroup1.add(optcredito);
        optcredito.setText("CREDITO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(optcontado)
                .addGap(18, 18, 18)
                .addComponent(optcredito)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optcontado)
                    .addComponent(optcredito))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 240, 90));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfecha.setText("aaaa-mm-dd");
        jPanel3.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 30));

        btnbuscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscarcliente.setContentAreaFilled(false);
        jPanel3.add(btnbuscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 200));

        txtidpersonal.setText("1");
        jPanel1.add(txtidpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 20, 20));

        txtnombrepersonal.setText("user");
        jPanel1.add(txtnombrepersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, 20));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnsalir.setToolTipText("BOTON SALIR");
        btnsalir.setContentAreaFilled(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
         dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturaCabVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturaCabVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturaCabVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturaCabVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturaCabVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnaceptar;
    public javax.swing.JButton btnaceptar2;
    public javax.swing.JButton btnaceptar3;
    public javax.swing.JButton btnadd;
    public javax.swing.JButton btnanular;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnbuscarcliente;
    public javax.swing.JButton btnbuscarfactura;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btndell;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnimprimir;
    public javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JRadioButton optcontado;
    public javax.swing.JRadioButton optcredito;
    public javax.swing.JTable tablabuscadorproducto;
    public javax.swing.JTable tablacliente;
    public javax.swing.JTable tabladetalle;
    public javax.swing.JTable tablafactura;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtbuscarproducto;
    public javax.swing.JTextField txtcantidad;
    public javax.swing.JTextField txtcliente;
    public javax.swing.JLabel txtestado;
    public javax.swing.JLabel txtfecha;
    public javax.swing.JTextField txtfiltrocliente;
    public javax.swing.JTextField txtfin;
    public javax.swing.JLabel txtid;
    public javax.swing.JLabel txtidpersonal;
    public javax.swing.JTextField txtidproducto;
    public javax.swing.JTextField txtinicio;
    public javax.swing.JTextField txtliquidacion10;
    public javax.swing.JTextField txtliquidacion5;
    public javax.swing.JTextField txtliquidaciontotal;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JLabel txtnombrepersonal;
    public javax.swing.JLabel txtnombreproducto;
    public javax.swing.JTextField txtnumero;
    public javax.swing.JTextField txtruc;
    public javax.swing.JTextField txttotal10;
    public javax.swing.JTextField txttotal5;
    public javax.swing.JTextField txttotalexenta;
    public javax.swing.JTextField txttotalfactura;
    // End of variables declaration//GEN-END:variables
}
