/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ciudadControlador;
import controlador.clienteControlador;
import controlador.facturaControlador;
import controlador.loginControlador;
import controlador.personalControlador;
import controlador.productoControlador;
import controlador.proveedorControlador;
import controlador.usuarioControlador;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import modelo.ciudadModelo;
import modelo.clienteModelo;
import modelo.facturaModelo;
import modelo.loginModelo;
import modelo.personalModelo;
import modelo.productoModelo;
import modelo.proveedorModelo;
import modelo.usuarioModelo;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ALUMNO
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);//para maximizar
        //colocar icono a la barra de tarea
        URL url = getClass().getResource("/imagenes/healthcare.png");
        ImageIcon img = new ImageIcon(url);
        this.setIconImage(img.getImage());
        Fecha();
        Timer time = new Timer(250, new escucha());
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        fondo_pantalla = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtnombreusuario = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttipodepersonal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnciudad = new javax.swing.JMenu();
        btnpersonal = new javax.swing.JMenuItem();
        btnclientes = new javax.swing.JMenuItem();
        btnproveedor = new javax.swing.JMenuItem();
        btnproductos = new javax.swing.JMenuItem();
        btnusuario = new javax.swing.JMenuItem();
        btnusuario1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnproducto = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jPanel2.add(fondo_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 580, 475));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombreusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtnombreusuario.setText("usuario");
        jPanel1.add(txtnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 30));

        txthora.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txthora.setForeground(new java.awt.Color(255, 255, 255));
        txthora.setText("hora");
        jPanel1.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(255, 255, 255));
        txtfecha.setText("fecha");
        jPanel1.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reloj.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        jLabel3.setText("\n");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 40, -1));

        txttipodepersonal.setText("tipo");
        jPanel1.add(txttipodepersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/power (1).png"))); // NOI18N
        jButton2.setToolTipText("PRSIONA \"ESC\" ");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        btnciudad.setForeground(new java.awt.Color(0, 102, 102));
        btnciudad.setText("REFERENCIALES");
        btnciudad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnpersonal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnpersonal.setForeground(new java.awt.Color(0, 102, 102));
        btnpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        btnpersonal.setText("PERSONAL");
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });
        btnciudad.add(btnpersonal);

        btnclientes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnclientes.setForeground(new java.awt.Color(0, 102, 102));
        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cliente.png"))); // NOI18N
        btnclientes.setText("CLIENTES");
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        btnciudad.add(btnclientes);

        btnproveedor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnproveedor.setForeground(new java.awt.Color(0, 102, 102));
        btnproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N
        btnproveedor.setText("PROVEEDOR");
        btnproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedorActionPerformed(evt);
            }
        });
        btnciudad.add(btnproveedor);

        btnproductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnproductos.setForeground(new java.awt.Color(0, 102, 102));
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        btnproductos.setText("PRODUCTOS");
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        btnciudad.add(btnproductos);

        btnusuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnusuario.setForeground(new java.awt.Color(0, 102, 102));
        btnusuario.setText("USUARIO");
        btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarioActionPerformed(evt);
            }
        });
        btnciudad.add(btnusuario);

        btnusuario1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnusuario1.setForeground(new java.awt.Color(0, 102, 102));
        btnusuario1.setText("CIUDAD");
        btnusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuario1ActionPerformed(evt);
            }
        });
        btnciudad.add(btnusuario1);

        jMenuBar1.add(btnciudad);

        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setText("VENTAS");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        jMenuItem1.setText("FACTURA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setForeground(new java.awt.Color(0, 102, 102));
        jMenu5.setText("REPORTES");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnproducto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnproducto.setForeground(new java.awt.Color(0, 102, 102));
        btnproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        btnproducto.setText("PRODUCTOS");
        btnproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductoActionPerformed(evt);
            }
        });
        jMenu5.add(btnproducto);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem2.setText("CLIENTES");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem3.setText("PROVEEDORES");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setBackground(new java.awt.Color(0, 102, 102));
        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem4.setText("PERSONALES");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Statement st = null;
    ResultSet rs = null;

    public void Fecha() {
        String sql = "select curdate() as fecha";
        try {

            st = conexion.conexion.sta(st);
            rs = st.executeQuery(sql);
            rs.next();

            txtfecha.setText(rs.getString("fecha"));

            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            String fecha = formato.format(date);
            st.close();
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No conecta");
            //JOptionPane.showMessageDialog(null, "Error" + e, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    class escucha implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar ahora = Calendar.getInstance();
            int hor = ahora.get(Calendar.HOUR_OF_DAY);
            int min = ahora.get(Calendar.MINUTE);
            int seg = ahora.get(Calendar.SECOND);
            txthora.setText(hor + ":" + min + ":" + seg);
        }
    }
    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        personalVista vista = new personalVista();
        personalModelo modelo = new personalModelo(vista);
        personalControlador controlador = new personalControlador(vista, modelo);
        modelo.inicio();
        vista.setVisible(true);
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        clientesVista vista = new clientesVista();
        clienteModelo modelo = new clienteModelo(vista);
        clienteControlador controlador = new clienteControlador(vista, modelo);
        modelo.inicio();
        vista.setVisible(true);

    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedorActionPerformed
        proveedorVista vista = new proveedorVista();
        proveedorModelo modelo = new proveedorModelo(vista);
        proveedorControlador contralador = new proveedorControlador(modelo, vista);
        modelo.inicio();
        vista.setVisible(true);

    }//GEN-LAST:event_btnproveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        facturaCabVista vista = new facturaCabVista();
        facturaModelo modelo = new facturaModelo(vista);
        facturaControlador controlador = new facturaControlador(vista, modelo);
        modelo.inicio();
        //vista.txtidpersonal.setText(txtidpersonal.getText());
        vista.txtnombrepersonal.setText(txtnombreusuario.getText());
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductoActionPerformed

        Connection conn = null;
        String RUTALOCAL = System.getProperty("user.dir");
        try {
            conn = conexion.conexion.Enlace(conn);
            HashMap parametros = new HashMap();
            parametros.put("usuario", txtnombreusuario.getText());
            JasperPrint jp = JasperFillManager.fillReport(RUTALOCAL + "/src/informes/producto.jasper", parametros, conn);
            JasperViewer view = new JasperViewer(jp, false);
            view.setTitle("PROUCTO");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);

            view.setVisible(true);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnproductoActionPerformed

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        productoVista vista = new productoVista();
        productoModelo modelo = new productoModelo(vista);
        productoControlador controlador = new productoControlador(modelo, vista);

        modelo.inicio();
        vista.setVisible(true);


    }//GEN-LAST:event_btnproductosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Connection conn = null;
        String RUTALOCAL = System.getProperty("user.dir");
        try {
            conn = conexion.conexion.Enlace(conn);
            HashMap parametros = new HashMap();
            parametros.put("usuario", txtnombreusuario.getText());
            JasperPrint jp = JasperFillManager.fillReport(RUTALOCAL + "/src/informes/proveedor.jasper", parametros, conn);
            JasperViewer view = new JasperViewer(jp, false);
            view.setTitle("PROVEEDOR");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);

            view.setVisible(true);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Connection conn = null;
        String RUTALOCAL = System.getProperty("user.dir");
        try {
            conn = conexion.conexion.Enlace(conn);
            HashMap parametros = new HashMap();
            parametros.put("usuario", txtnombreusuario.getText());
            JasperPrint jp = JasperFillManager.fillReport(RUTALOCAL + "/src/informes/clientes.jasper", parametros, conn);
            JasperViewer view = new JasperViewer(jp, false);
            view.setTitle("CLIENTES");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);

            view.setVisible(true);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int r = JOptionPane.showConfirmDialog(null, "DESEA CERRAR SESIÓN", "PREGUNTA", 0);

        if (r == 0) {
            login vista = new login();
            loginModelo modelo = new loginModelo(vista);
            loginControlador controlador = new loginControlador(vista, modelo);

            modelo.inicio();
            
            
            vista.setVisible(true);
            super.dispose();
        } else {

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Connection conn = null;
        String RUTALOCAL = System.getProperty("user.dir");
        try {
            conn = conexion.conexion.Enlace(conn);
            HashMap parametros = new HashMap();
            parametros.put("usuario", txtnombreusuario.getText());
            JasperPrint jp = JasperFillManager.fillReport(RUTALOCAL + "/src/informes/personal.jasper", parametros, conn);
            JasperViewer view = new JasperViewer(jp, false);
            view.setTitle("PERSONALES");
            view.setExtendedState(Frame.MAXIMIZED_BOTH);

            view.setVisible(true);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarioActionPerformed
        usuarioVista vista = new usuarioVista();
        usuarioModelo modelo = new usuarioModelo(vista);
        usuarioControlador controlador = new usuarioControlador(vista, modelo);
        modelo.inicio();
        vista.setVisible(true);
    }//GEN-LAST:event_btnusuarioActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int r = JOptionPane.showConfirmDialog(null, "DESEA CERRAR SESIÓN", "PREGUNTA", 0);
            if (r == 0) {
                login vista = new login();
                loginModelo modelo = new loginModelo(vista);
                loginControlador controlador = new loginControlador(vista, modelo);

                modelo.inicio();
                vista.setVisible(true);
                super.dispose();
            } else {

            }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void btnusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuario1ActionPerformed
         ciudadVista vista= new ciudadVista();
         ciudadModelo modelo= new ciudadModelo(vista);
         ciudadControlador controlador = new ciudadControlador(modelo, vista);
         modelo.inicio();
         vista.setVisible(true);
    }//GEN-LAST:event_btnusuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnciudad;
    public javax.swing.JMenuItem btnclientes;
    public javax.swing.JMenuItem btnpersonal;
    private javax.swing.JMenuItem btnproducto;
    public javax.swing.JMenuItem btnproductos;
    public javax.swing.JMenuItem btnproveedor;
    private javax.swing.JMenuItem btnusuario;
    private javax.swing.JMenuItem btnusuario1;
    private javax.swing.JLabel fondo_pantalla;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel txtfecha;
    public javax.swing.JLabel txthora;
    public javax.swing.JLabel txtnombreusuario;
    public javax.swing.JLabel txttipodepersonal;
    // End of variables declaration//GEN-END:variables

}
