/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;



import com.sun.awt.AWTUtilities;
import controlador.loginControlador;
import java.net.URL;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import vista.login;

/**
 *
 * @author ALUMNO
 */
public class Inicio_Sistema extends javax.swing.JFrame {

    /**
     * Creates new form splashScreen
     */
    public Inicio_Sistema() {
        initComponents();
          URL url = getClass().getResource("/imagenes/healthcare.png");
        ImageIcon img = new ImageIcon(url);
        this.setIconImage(img.getImage());
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);

//        new Thread() {
//            public void run() {
//                for (int i = 0; i < 50; i++) {
//                    
//                   
//                    try {
//                        sleep(60);
//                        pbrcargar.setValue(i);
//
//                        if (pbrcargar.getValue() <= 10) {
//                            txtcontenido.setText("INICIANDO");
//
//                        } else if (pbrcargar.getValue() <= 30) {
//                            txtcontenido.setText("CONECTANDO A LA BASE DE DATOS");
//
//                        } else {
//                            txtcontenido.setText("REALIZANDO AJUSTES");
//                        }
//                    } catch (InterruptedException ex) {
//                        java.util.logging.Logger.getLogger(splashScreen.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                   
//
//                }
                login vista = new login();
                loginModelo modelo = new loginModelo(vista);
                loginControlador controlador = new loginControlador(vista, modelo);

                modelo.inicio();
                vista.setVisible(true);
                dispose();
//            }
//        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
